language: rust
rust:
  - 1.34.0
  - 1.35.0
  - 1.36.0
  - 1.37.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    # Rustfmt
    - rust: stable
      install:
        - rustup component add rustfmt-preview
      before_script:
        - cargo fmt --version
      script:
        - cargo fmt -- --check

    # Clippy
    - rust: stable
      install:
        - rustup component add clippy-preview
      script:
        # Fail if clippy output contains "error:" or "warning:"
        - cargo clippy 2>&1 | tee ./clippy.out && ! grep -qe  "error:\|warning:" ./clippy.out

    # Test coverage (with Tarpaulin)
    - env: TARPAULIN_VERSION="0.8.6"
      rust: stable
      # To avoid "Error: EPERM: operation not permitted" error (see https://github.com/valery-barysok/session-file-store/issues/58)
      sudo: true
      install:
        - curl -sL https://github.com/xd009642/tarpaulin/releases/download/$TARPAULIN_VERSION/cargo-tarpaulin-$TARPAULIN_VERSION-travis.tar.gz | tar xvz -C $HOME/.cargo/bin
      script:
        - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID


script:
  - cargo test && cargo test -- --ignored
cache:
  cargo: true
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

addons:
  apt:
    packages:
      - libssl-dev  # Required for tarpaulin
